import { useEffect, useState } from 'react'
import { useRoomStore } from '../store/roomStore'
import { newBriefRoom, validateBrief, KINDS, FLOORS, WALLS, FINISHES, LIGHTS } from '../../shared/brief.mjs'
import PlanMeasure from './PlanMeasure'
import BriefChat from './BriefChat'

const SECTIONS=[['project','Project & client'],['room','Room & floorplan'],['direction','Colors & atmosphere'],['surfaces','Surfaces & light'],['details','Practical details']]
const Field=({label,value,onChange,type='text',options,wide=false})=><label className={`brief-field ${wide?'wide':''}`}><span>{label}</span>{options?<select aria-label={label} value={value??''} onChange={e=>onChange(e.target.value)}>{options.map(v=><option key={v} value={v}>{v||'Choose…'}</option>)}</select>:type==='textarea'?<textarea aria-label={label} rows="3" value={value??''} onChange={e=>onChange(e.target.value)}/>:<input aria-label={label} type={type} step={type==='number'?'any':undefined} value={value??''} onChange={e=>onChange(type==='number'?(e.target.value===''?null:Number(e.target.value)):e.target.value)}/>}</label>
const Check=({label,value,onChange})=><label className="brief-checkbox"><input type="checkbox" checked={!!value} onChange={e=>onChange(e.target.checked)}/>{label}</label>
// The Brief is written here, in the app. The draft lives in the project itself
// (so autosave and recovery keep it); nothing is uploaded or exported.
export default function BriefEditor({onReview,onDiscard}){
  const doc=useRoomStore(s=>s.briefDraft),setDoc=fn=>useRoomStore.getState().setBriefDraft(fn(useRoomStore.getState().briefDraft))
  const [section,setSection]=useState('project'),[roomIndex,setRoomIndex]=useState(0),[messages,setMessages]=useState([]),[status,setStatus]=useState(''),[assistant,setAssistant]=useState(''),[proposal,setProposal]=useState(null),[undo,setUndo]=useState(null),[outlineText,setOutlineText]=useState('')
  const room=doc.rooms[roomIndex],attachment=doc.attachments.find(a=>a.id===doc.plan.attachmentId)
  useEffect(()=>setOutlineText(room.outline.map(p=>`${p.x}, ${p.z}`).join('\n')),[roomIndex,room.outline])
  function edit(fn){setDoc(d=>{const n=structuredClone(d);fn(n);n.review.approved=false;return n});setStatus('');setProposal(null)}
  function review(){const result=validateBrief(doc);setMessages(result.errors);if(result.errors.length){setStatus('Complete the listed checks before creating the room.');return}onReview()}
  const setRoom=(key,value,geometry=false)=>edit(d=>{d.rooms[roomIndex][key]=value;if(geometry){d.rooms[roomIndex].geometryVerified=false;d.rooms[roomIndex].openingsVerified=false;d.plan.layoutVerified=false}})
  const note=(key,label)=> <Field key={key} label={label} value={room.notes[key]} type="textarea" onChange={v=>edit(d=>{d.rooms[roomIndex].notes[key]=v})}/>
  const surface=(key,value)=>edit(d=>{d.rooms[roomIndex].surfaces[key]=value})
  async function attach(file){if(!file)return;setMessages([]);try{
    if(!['image/png','image/jpeg','application/pdf'].includes(file.type)||file.size>2*1024*1024)throw new Error('Use a PDF, PNG or JPEG up to 2 MB. Export a smaller plan if needed.')
    const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(new Error('Could not read this file.'));r.readAsDataURL(file)})
    edit(d=>{const a={id:crypto.randomUUID(),name:file.name,mime:file.type,dataUrl};d.attachments=[a];d.plan.attachmentId=a.id;d.plan.source='attachment';d.plan.layoutVerified=false;d.rooms.forEach(r=>{r.geometryVerified=false;r.openingsVerified=false})})
  }catch(e){setMessages([e.message])}}
  return <div className="brief-app"><header className="brief-header"><span>OFFICIAL DESIGN BRIEF · V1</span></header>
    <div className="brief-editor-layout"><nav className="brief-nav">{SECTIONS.map(([id,label])=><button key={id} aria-pressed={section===id} onClick={()=>setSection(id)}>{label}</button>)}<button onClick={()=>{if(window.confirm('Discard this Brief and start over?'))onDiscard()}}>Discard this Brief</button></nav>
      <main className="brief-editor-main"><span className="brief-eyebrow">A SPACE THAT FEELS LIKE YOU</span><h1>A beautiful room.<br/>A clear place to start.</h1><p className="brief-lead">Capture the foundation. Choose the furniture together later.</p>
        <div className="brief-editor-grid"><section className="brief-form"><h2>{SECTIONS.find(x=>x[0]===section)[1]}</h2>
          {section!=='project'&&<div className="brief-room-picker"><label className="brief-field"><span>Editing room</span><select value={roomIndex} onChange={e=>setRoomIndex(Number(e.target.value))}>{doc.rooms.map((r,i)=><option key={r.id} value={i}>{r.name||`Room ${i+1}`}</option>)}</select></label><strong>{room.name||`Room ${roomIndex+1}`}</strong><button onClick={()=>{const next=newBriefRoom(doc.rooms.length+1);next.id=crypto.randomUUID();edit(d=>{d.rooms.push(next);d.plan.layoutVerified=false});setRoomIndex(doc.rooms.length)}} disabled={doc.rooms.length>=30}>Add room</button>{doc.rooms.length>1&&<button onClick={()=>{edit(d=>{d.rooms.splice(roomIndex,1);d.plan.layoutVerified=false});setRoomIndex(0)}}>Remove room</button>}</div>}
          <div className="brief-fields">
            {section==='project'&&<>{Object.entries({name:'Project name',client:'Client name',studio:'Studio / company',designer:'Designer'}).map(([key,label])=><Field key={key} label={label} value={doc.project[key]} onChange={v=>edit(d=>{d.project[key]=v})}/>)}<Field label="Measurement units" options={['m','ft']} value={doc.units} onChange={v=>edit(d=>{const k=v===d.units?1:v==='m'?.3048:1/.3048;d.rooms.forEach(r=>{for(const key of ['x','z','width','depth','height'])if(r[key]!==null)r[key]*=k;r.outline.forEach(p=>{p.x*=k;p.z*=k});r.openings.forEach(o=>{for(const key of ['offset','width','height','sill'])if(o[key]!==null)o[key]*=k})});d.units=v})}/><p className="brief-caption wide">Measurements are converted when units change. Feet use decimals, not feet-and-inches notation.</p></>}
            {section==='room'&&<>
              <div className="brief-plan-upload wide"><h3>Your floorplan</h3><p>Attach a blueprint, or enter a measured plan using room positions and dimensions below.</p><input aria-label="Attach floorplan" type="file" accept="image/png,image/jpeg,application/pdf" onChange={e=>attach(e.target.files[0])}/><p>PDF, PNG or JPEG · 2 MB maximum</p>{attachment&&<><strong>{attachment.name}</strong><button onClick={()=>edit(d=>{d.attachments=[];d.plan.attachmentId=null;d.plan.source='measured';d.plan.layoutVerified=false;d.rooms.forEach(r=>{r.geometryVerified=false;r.openingsVerified=false})})}>Remove plan</button>{attachment.mime.startsWith('image/')?<PlanMeasure key={attachment.id+doc.units} attachment={attachment} units={doc.units} onMeasure={value=>edit(d=>{Object.assign(d.rooms[roomIndex],value.room,{outline:[],geometryVerified:false,openingsVerified:false,measurementSource:'Dimensioned floorplan'});d.plan.reference=value.reference;d.plan.layoutVerified=false})}/>:<p>PDF retained in the official brief. Enter its printed measurements below, or upload a PNG/JPEG page for scale measurement. Automatic PDF reading is not connected.</p>}</>}</div>
              <Field label="Plan reference / known scale" wide value={doc.plan.reference} onChange={v=>edit(d=>{d.plan.reference=v;d.plan.layoutVerified=false})}/><Field label="Plan page" type="number" value={doc.plan.page} onChange={v=>edit(d=>{d.plan.page=v;d.plan.layoutVerified=false})}/>
              <Field label="Room name" value={room.name} onChange={v=>setRoom('name',v)}/><Field label="Room type" options={KINDS} value={room.kind} onChange={v=>setRoom('kind',v)}/>
              {['width','depth','height','x','z','floor'].map(key=><Field key={key} label={key==='height'?`Ceiling height (${doc.units})`:key==='floor'?'Floor (ground = 0)':`${key.toUpperCase()} (${doc.units})`} type="number" value={room[key]} onChange={v=>setRoom(key,v,true)}/>)}
              <p className="brief-caption wide">X and Z locate each room’s top-left corner on one shared plan. X runs right; Z runs down. Width and depth are inside finished wall faces. Separate adjacent rooms by the measured wall thickness.</p>
              <Field label="Measurement source" options={['','Designer measured','Dimensioned floorplan']} value={room.measurementSource} onChange={v=>setRoom('measurementSource',v,true)}/>
              <details className="wide"><summary>Custom measured outline (optional)</summary><p>For a nonrectangular room, enter X, Z pairs clockwise, one point per line. Start from the room’s local top-left bounding corner. Blank uses a rectangle. No holes or curved walls.</p><textarea aria-label="Measured outline points" rows="5" value={outlineText} onChange={e=>setOutlineText(e.target.value)}/><button onClick={()=>{const points=outlineText.trim()?outlineText.trim().split('\n').map(l=>{const [x,z]=l.split(',').map(Number);return {x,z}}):[];if(points.some(p=>!Number.isFinite(p.x)||!Number.isFinite(p.z))){setMessages(['Use one X, Z coordinate pair per line.']);return}setRoom('outline',points,true)}}>Use this outline</button></details>
              <div className="wide"><Check label="I verified the room dimensions, outline and ceiling height." value={room.geometryVerified} onChange={v=>setRoom('geometryVerified',v)}/><h3>Doors & windows</h3><p>Rectangles: edge 0 = top (left → right), 1 = right (top → bottom), 2 = bottom (right → left), 3 = left (bottom → top). Custom outlines follow point order. Offsets start at the edge’s first point.</p>
                {room.openings.map((o,i)=><div className="brief-opening" key={o.id}><div className="brief-fields"><Field label="Type" options={['door','window','passage']} value={o.type} onChange={v=>edit(d=>{d.rooms[roomIndex].openings[i].type=v;d.rooms[roomIndex].openingsVerified=false})}/>{['edge','offset','width','height','sill'].map(key=><Field key={key} label={key==='edge'?'Wall edge number':`${key} (${doc.units})`} type="number" value={o[key]} onChange={v=>edit(d=>{d.rooms[roomIndex].openings[i][key]=v;d.rooms[roomIndex].openingsVerified=false})}/>)}</div><button onClick={()=>edit(d=>{d.rooms[roomIndex].openings.splice(i,1);d.rooms[roomIndex].openingsVerified=false})}>Remove opening</button></div>)}
                <button onClick={()=>edit(d=>{d.rooms[roomIndex].openings.push({id:crypto.randomUUID(),type:'door',edge:0,offset:null,width:null,height:null,sill:0});d.rooms[roomIndex].openingsVerified=false})}>Add opening</button><Check label="I recorded and verified all openings, including none where appropriate." value={room.openingsVerified} onChange={v=>setRoom('openingsVerified',v)}/><Check label="I verified the complete plan, room positions and scale." value={doc.plan.layoutVerified} onChange={v=>edit(d=>{d.plan.layoutVerified=v})}/>
              </div>{note('fixedFeatures','Fixed features and measured references')}{note('preserveArchitecture','Architectural details to preserve')}
            </>}
            {section==='direction'&&<>{['wallColor','accentColor','trimColor'].map(key=><div className="brief-color" key={key}><Field label={{wallColor:'Main / wall color',accentColor:'Accent color',trimColor:'Trim color'}[key]} type="color" value={room.surfaces[key]} onChange={v=>surface(key,v)}/><Field label="HEX code" value={room.surfaces[key]} onChange={v=>surface(key,v)}/></div>)}{note('feeling','How should the room feel?')}{note('avoidColors','Colors to leave out')}{note('inspiration','Inspiration / mood board references')}{note('paintReference','Exact paint references')}{note('roomPurpose','What will this space make possible?')}{note('roomUsers','Who uses this room?')}</>}
            {section==='surfaces'&&<><Field label="Floor material" options={FLOORS} value={room.surfaces.floor} onChange={v=>surface('floor',v)}/><Field label="Floor finish" options={FINISHES} value={room.surfaces.floorFinish} onChange={v=>surface('floorFinish',v)}/><Field label="Floor tint" type="color" value={room.surfaces.floorColor} onChange={v=>surface('floorColor',v)}/><Field label="Wall material" options={WALLS} value={room.surfaces.wall} onChange={v=>surface('wall',v)}/><Field label="Wall finish" options={FINISHES} value={room.surfaces.wallFinish} onChange={v=>surface('wallFinish',v)}/><Field label="Texture tile size (meters)" type="number" value={room.surfaces.textureScale} onChange={v=>surface('textureScale',v)}/><Field label="Lighting preview" options={LIGHTS} value={room.lighting} onChange={v=>setRoom('lighting',v)}/>{[['floorDetail','Plank / tile size and direction'],['surfaceReferences','Exact material references'],['ceiling','Ceiling details (flat is supported)'],['trim','Trim details'],['daylight','Daylight orientation'],['lightNotes','Lighting needs and existing points']].map(([k,l])=>note(k,l))}<p className="brief-caption wide">Preview materials use procedural textures at the selected meter scale. Reference products, ceiling details and lighting requirements remain notes where the renderer does not support them.</p></>}
            {section==='details'&&<>{[['needs','Everyday needs / maintenance'],['access','Access, circulation & comfort'],['avoidMaterials','Materials to avoid'],['budget','Room preparation budget'],['currency','Currency'],['budgetCovers','Budget inclusions (finishes, labor, fees)'],['scope','Project scope'],['targetDate','Target completion date'],['constraints','Constraints & non-negotiables'],['questions','Open questions']].map(([k,l])=>note(k,l))}<div className="wide"><h3>Client review</h3><Field label="Reviewed by" value={doc.review.reviewedBy} onChange={v=>edit(d=>{d.review.reviewedBy=v})}/><Field label="Review date" type="date" value={doc.review.date} onChange={v=>edit(d=>{d.review.date=v})}/><Check label="The designer and client reviewed this brief." value={doc.review.approved} onChange={v=>setDoc(d=>({...d,review:{...d.review,approved:v}}))}/></div></>}
          </div>
        </section><BriefChat doc={doc} roomId={room.id} edit={edit}/></div>
        <div className="brief-editor-footer"><p role="status">{status||'Your Brief saves with the project as you type.'}</p><button className="brief-primary" onClick={review}>Review and create the room</button></div>
        {!!messages.length&&<section className="brief-error" role="alert"><h3>Before this brief can build a room</h3><ul>{messages.map((m,i)=><li key={i}>{m}</li>)}</ul></section>}
      </main></div></div>
}
